### PR TITLE
Updated code to include Pin mode and Modifier for the StepGen so now …

### PR DESCRIPTION
**Pull request by Geramy**
…open drain can be used for external stepper drivers.

### CODE REVIEW

**Comment by cakeslob** [comment]
Hey Geramy, Im fine with adding and testing it out and everything, if its something you think other people would use, but I have some questions/requests.

Is there a use case where you would need to set a stepgen pin to and input? 
Do you have a config.txt example for this change? 

Can you make this an optional config entry?  As in, if its omited from the config.txt, it will default to whatever it is now

**Comment by scottalford75** [comment]
My proposal would not to merge this. 
1. Remora OS5 and LPC1768/9 is a legacy version
2. SKR v1.1 is not readily available any more

**Comment by Geramy** [comment]
That’s fine we don’t have to merge this, I was actually using it in reverse instead of outputting voltage to drive the stepper I was sinking it to ground. This was because I have 5v drivers and not 3.3v drivers. It didn’t really work either I mean it did for a second or two but then the board crashed because it’s not meant to sink 5v haha, or push 5v either. More of a hack you can kick it.

**Comment by cakeslob** [comment]
OK, sounds good to me. I just didnt want it to get too stale.

**Pull request closed without merging**
