### PR TITLE
Ender3 updates

### PR DESCRIPTION
**Pull request by dlarue**
updated Creality Ender 3 sample config after some testing.

### CODE REVIEW

**Review by scottalford75 — CHANGES_REQUESTED** [review]
Hi Doug, 

The MKS Sbase config.txt file does not look correct for the extruder fan switch. You pull request is proposing to change the comment to PWM, which it is not.

**Comment by dlarue** [comment]
ah, you are referring to the hal file, my extruder has 2 fans, the hotend fan blowing on the coldend section of the hotend and the part cooling fan.  There are M106 and M107 which control the PWM/fan speed of the part cooling fan.
my M106:
#!/usr/bin/env python2

# Note! Change the above "python2" to "python" is not using Arch Linux

# M code to set Fan speed
# M106 in your G code program will run the python code in this file, 
# passing the P and Q variables as command line arguments.

import sys
import hal

Mcode = 'M106'
usage = 'Fan speed'
pin = 'SP'
SP_signal = 'ext0-cooling-SP'

h = hal.component(Mcode)

if( len(sys.argv) < 2 ):
    print "Usage: " + Mcode + " Pn - where n is the " + usage
    quit()

# P and Q command line arguments
P = sys.argv[1]
Q = sys.argv[2]

#Reprap fan speed is between 0 and 255 (0% to 100%) therefore we need to scale the setpoint

SP = (float(P) / 255) * 100

print 'Setting ' + usage + ' to ' + str(SP) + '%'

h.newpin(pin, hal.HAL_FLOAT, hal.HAL_OUT)
hal.connect(Mcode + '.' + pin, SP_signal)

h[pin] = SP

**Comment by scottalford75** [comment]
No, the config.txt file 

image

**Comment by dlarue** [comment]
Ah, so that should be
"Type": "PWM"

I thought it was operating as PWM'ed.

**Comment by scottalford75** [comment]
This is the on / off for the hot end cooling fan. The part cooling fan is on PWM.

**Comment by dlarue** [comment]
Sorry, it's been a while since I was running the MKS board as the last month or so was with the SKR and the tmc2208 drivers.
I think I wired the part cooling fan to PWM pin 2.4
and it would seem the Extruder fan was on a switched connection. I'll see if I can fix the code in my branch without doing a new pull request.

**Comment by dlarue** [comment]
Scott, I've updated the comment on my branch, do I need to resubmit a pull request on that branch or does it somehow reflect back here?

**Comment by scottalford75** [comment]
Hi Doug, Looks ok. I'll merge into main.
Thanks

**Pull request merged**
